"""Canonical OpenAPI 3 contract for the SEGS HTTP API.

Interactive ``/docs`` stays off (no public route enumeration). The checked-in
spec is the contract:

* ``docs/openapi.yaml`` — human/tooling document (paths, schemas, security)
* ``infra/openapi.yaml`` — same operations plus API Gateway HTTP API
  integrations (VPC link → internal ALB). Terraform sets ``body`` from it.

Regenerate both files after adding or renaming a route:

    python -m backend.api.openapi
"""
from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path
from typing import Any

import yaml
from fastapi.openapi.utils import get_openapi

from backend.paths import REPO_ROOT

DOCS_SPEC = REPO_ROOT / "docs" / "openapi.yaml"
APIGW_SPEC = REPO_ROOT / "infra" / "openapi.yaml"

_API_PREFIXES = ("/api", "/scim")
_HEADER = (
    "# Generated by python -m backend.api.openapi — do not edit by hand.\n"
    "# Add or rename FastAPI routes, then regenerate so API Gateway stays in sync.\n"
)

_SECURITY_SCHEMES = {
    "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": (
            "Stateful JWT (RFC 6750). Same token as the seg_session cookie; "
            "jti is stored server-side."
        ),
    },
    "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "seg_session",
        "description": "Session cookie set at login. Same credential as Bearer.",
    },
    "scimBearer": {
        "type": "http",
        "scheme": "bearer",
        "description": "SCIM 2.0 bearer (SEG_SCIM_BEARER_TOKEN) or an admin JWT.",
    },
}

_PUBLIC_PATHS = {
    ("/api/health", "get"),
    ("/api/setup/status", "get"),
    ("/api/setup", "post"),
    ("/api/auth/login", "post"),
    ("/api/auth/login/webauthn", "post"),
    ("/api/auth/passkeys/assert/options", "post"),
    ("/api/auth/passkeys/assert", "post"),
}

_ALB_INTEGRATION = {
    "type": "HTTP_PROXY",
    "httpMethod": "ANY",
    "connectionType": "VPC_LINK",
    "connectionId": "${vpc_link_id}",
    "uri": "${alb_listener_arn}",
    "payloadFormatVersion": "1.0",
    "timeoutInMillis": 30000,
}

_INTEGRATION_REF = {
    "$ref": "#/components/x-amazon-apigateway-integrations/alb",
}


def _is_api_path(path: str) -> bool:
    return path == "/api" or any(
        path == p or path.startswith(p + "/") for p in _API_PREFIXES
    )


def _keep_path(path: str) -> bool:
    if path in ("/", "/{full_path}"):
        return False
    return _is_api_path(path)


def _downgrade_nullable(node: Any) -> Any:
    """OpenAPI 3.0-ish nullables so API Gateway HTTP API import stays happy."""
    if isinstance(node, list):
        return [_downgrade_nullable(x) for x in node]
    if not isinstance(node, dict):
        return node
    out = {k: _downgrade_nullable(v) for k, v in node.items()}
    alts = out.get("anyOf")
    if isinstance(alts, list) and len(alts) == 2:
        types = [a.get("type") for a in alts if isinstance(a, dict)]
        if "null" in types:
            other = next(a for a in alts if isinstance(a, dict) and a.get("type") != "null")
            merged = dict(other)
            merged["nullable"] = True
            extras = {k: v for k, v in out.items() if k != "anyOf"}
            extras.update(merged)
            return extras
    types = out.get("type")
    if isinstance(types, list) and "null" in types:
        non_null = [t for t in types if t != "null"]
        if len(non_null) == 1:
            out["type"] = non_null[0]
            out["nullable"] = True
    return out


def _security_for(path: str, method: str) -> list[dict]:
    if (path, method) in _PUBLIC_PATHS:
        return []
    if path.startswith("/scim/"):
        return [{"scimBearer": []}]
    return [{"bearerAuth": []}, {"cookieAuth": []}]


def build_spec(*, app=None) -> dict:
    """OpenAPI 3.0 document for /api and /scim only (no SPA catch-all)."""
    if app is None:
        from backend.api.main import create_app
        app = create_app()
    spec = get_openapi(
        title=app.title,
        version=app.version or "1.0.0",
        description=app.description or "",
        routes=app.routes,
        servers=getattr(app, "servers", None) or None,
        openapi_version="3.0.1",
    )
    spec["openapi"] = "3.0.1"
    spec["info"]["x-generated-by"] = "backend.api.openapi"
    paths = {
        path: item
        for path, item in (spec.get("paths") or {}).items()
        if _keep_path(path)
    }
    spec["paths"] = paths
    components = spec.setdefault("components", {})
    schemes = components.setdefault("securitySchemes", {})
    schemes.update(copy.deepcopy(_SECURITY_SCHEMES))
    for path, item in paths.items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method.startswith("x-") or method in ("parameters", "summary", "description"):
                continue
            if not isinstance(op, dict):
                continue
            sec = _security_for(path, method)
            if sec:
                op["security"] = sec
            else:
                op["security"] = []
    spec = _downgrade_nullable(spec)
    return spec


def build_apigw_spec(canonical: dict | None = None) -> dict:
    """Same operations, with HTTP API VPC-link integrations for Terraform ``body``."""
    spec = copy.deepcopy(canonical or build_spec())
    components = spec.setdefault("components", {})
    components["x-amazon-apigateway-integrations"] = {"alb": copy.deepcopy(_ALB_INTEGRATION)}
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method, op in list(item.items()):
            if method.startswith("x-") or method in ("parameters", "summary", "description"):
                continue
            if isinstance(op, dict):
                op["x-amazon-apigateway-integration"] = copy.deepcopy(_INTEGRATION_REF)
        if "get" in item and "head" not in item and isinstance(item["get"], dict):
            head = copy.deepcopy(item["get"])
            oid = str(head.get("operationId") or "get")
            head["operationId"] = oid + "Head"
            head["summary"] = (head.get("summary") or "GET") + " (HEAD)"
            head["x-amazon-apigateway-integration"] = copy.deepcopy(_INTEGRATION_REF)
            item["head"] = head
    return spec


def _dump(spec: dict) -> str:
    text = _HEADER + yaml.safe_dump(
        spec,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=88,
    )
    # Quote Terraform interpolations so the ALB listener ARN (colons) stays a YAML string.
    text = text.replace(
        "connectionId: ${vpc_link_id}",
        'connectionId: "${vpc_link_id}"',
    )
    text = text.replace(
        "uri: ${alb_listener_arn}",
        'uri: "${alb_listener_arn}"',
    )
    return text


def write_specs(*, docs_path: Path | None = None, apigw_path: Path | None = None) -> tuple[Path, Path]:
    canonical = build_spec()
    docs = Path(docs_path or DOCS_SPEC)
    apigw = Path(apigw_path or APIGW_SPEC)
    docs.parent.mkdir(parents=True, exist_ok=True)
    apigw.parent.mkdir(parents=True, exist_ok=True)
    docs.write_text(_dump(canonical), encoding="utf-8")
    apigw.write_text(_dump(build_apigw_spec(canonical)), encoding="utf-8")
    return docs, apigw


def operation_keys(spec: dict) -> set[tuple[str, str]]:
    out: set[tuple[str, str]] = set()
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method in item:
            if method.startswith("x-") or method in ("parameters", "summary", "description", "head"):
                continue
            out.add((path, method.lower()))
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write docs/openapi.yaml and infra/openapi.yaml")
    parser.add_argument("--check", action="store_true", help="Exit 1 if checked-in files are stale")
    args = parser.parse_args(argv)
    canonical = build_spec()
    apigw = build_apigw_spec(canonical)
    docs_text = _dump(canonical)
    apigw_text = _dump(apigw)
    if args.check:
        ok = (
            DOCS_SPEC.is_file()
            and APIGW_SPEC.is_file()
            and DOCS_SPEC.read_text(encoding="utf-8") == docs_text
            and APIGW_SPEC.read_text(encoding="utf-8") == apigw_text
        )
        if not ok:
            print("OpenAPI specs are stale. Run: python -m backend.api.openapi", file=sys.stderr)
            return 1
        print("OpenAPI specs are current.")
        return 0
    write_specs()
    print(f"Wrote {DOCS_SPEC.relative_to(REPO_ROOT)}")
    print(f"Wrote {APIGW_SPEC.relative_to(REPO_ROOT)}")
    print(f"{len(operation_keys(canonical))} operations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
