-- Postgres schema for SEGS when SEG_DATABASE_URL is set.
-- SQLite stores keep their own CREATE TABLE scripts for pytest.

CREATE TABLE IF NOT EXISTS copies (
    queue_id TEXT PRIMARY KEY,
    dest TEXT NOT NULL DEFAULT '',
    mailbox TEXT NOT NULL DEFAULT '',
    gmail_message_id TEXT NOT NULL DEFAULT '',
    gmail_thread_id TEXT NOT NULL DEFAULT '',
    from_addr TEXT NOT NULL DEFAULT '',
    subject TEXT NOT NULL DEFAULT '',
    to_addr TEXT NOT NULL DEFAULT '',
    verdict TEXT NOT NULL DEFAULT '',
    score DOUBLE PRECISION,
    disposition TEXT NOT NULL DEFAULT 'LOG',
    ai_provider TEXT NOT NULL DEFAULT '',
    ai_summary TEXT NOT NULL DEFAULT '',
    ai_model TEXT NOT NULL DEFAULT '',
    identity_done INTEGER NOT NULL DEFAULT 0,
    reputation_done INTEGER NOT NULL DEFAULT 0,
    static_done INTEGER NOT NULL DEFAULT 0,
    sandbox_done INTEGER NOT NULL DEFAULT 0,
    ai_done INTEGER NOT NULL DEFAULT 0,
    thread_ai_done INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'queued',
    stages_json TEXT NOT NULL DEFAULT '{}',
    meta_json TEXT NOT NULL DEFAULT '{}',
    rfc_message_id TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    ai_claimed_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    ai_claimed_by TEXT NOT NULL DEFAULT '',
    updated_at DOUBLE PRECISION NOT NULL DEFAULT 0
);
ALTER TABLE copies ADD COLUMN IF NOT EXISTS ai_claimed_at DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE copies ADD COLUMN IF NOT EXISTS ai_claimed_by TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_copies_thread ON copies(gmail_thread_id);
CREATE INDEX IF NOT EXISTS idx_copies_updated ON copies(updated_at);
CREATE INDEX IF NOT EXISTS idx_copies_status ON copies(status);
CREATE INDEX IF NOT EXISTS idx_copies_rfc ON copies(rfc_message_id);

ALTER TABLE copies ADD COLUMN IF NOT EXISTS origin_country TEXT NOT NULL DEFAULT '';
ALTER TABLE copies ADD COLUMN IF NOT EXISTS origin_city TEXT NOT NULL DEFAULT '';
ALTER TABLE copies ADD COLUMN IF NOT EXISTS origin_name TEXT NOT NULL DEFAULT '';
ALTER TABLE copies ADD COLUMN IF NOT EXISTS origin_lat DOUBLE PRECISION;
ALTER TABLE copies ADD COLUMN IF NOT EXISTS origin_lon DOUBLE PRECISION;
CREATE INDEX IF NOT EXISTS idx_copies_verdict_ai ON copies(ai_done, verdict, updated_at);
CREATE INDEX IF NOT EXISTS idx_copies_pending ON copies(ai_done, status);
CREATE INDEX IF NOT EXISTS idx_copies_origin ON copies(origin_country);

CREATE TABLE IF NOT EXISTS overview_stats (
    key TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL DEFAULT '{}',
    computed_at DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin','analyst','viewer')),
    created_at DOUBLE PRECISION NOT NULL,
    disabled INTEGER NOT NULL DEFAULT 0,
    email TEXT NOT NULL DEFAULT '',
    display_name TEXT NOT NULL DEFAULT '',
    external_id TEXT NOT NULL DEFAULT ''
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_users_external_id ON users(external_id);
CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    created_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    content_unlocked_until DOUBLE PRECISION NOT NULL DEFAULT 0,
    content_unlocked_thread TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS passkeys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    credential_id TEXT UNIQUE NOT NULL,
    public_key TEXT NOT NULL,
    sign_count INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT 'Passkey',
    created_at DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS webauthn_challenges (
    session_token TEXT PRIMARY KEY,
    challenge TEXT NOT NULL,
    purpose TEXT NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS pending_logins (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    purpose TEXT NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS history_cursor (
    user_email TEXT PRIMARY KEY,
    history_id TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS processed_message (
    user_email TEXT NOT NULL,
    message_id TEXT NOT NULL,
    seen_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (user_email, message_id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    dest TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    claimed_at DOUBLE PRECISION,
    claimed_by TEXT NOT NULL DEFAULT '',
    attempts INTEGER NOT NULL DEFAULT 0,
    UNIQUE(kind, dest)
);
CREATE INDEX IF NOT EXISTS idx_jobs_kind ON jobs(kind);
CREATE INDEX IF NOT EXISTS idx_jobs_kind_claimed ON jobs(kind, claimed_at);

CREATE TABLE IF NOT EXISTS followup (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    dest TEXT NOT NULL DEFAULT '',
    sender TEXT NOT NULL DEFAULT '',
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(kind, dest, sender)
);
CREATE INDEX IF NOT EXISTS idx_followup_kind ON followup(kind);

CREATE TABLE IF NOT EXISTS labels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    queue_id TEXT NOT NULL UNIQUE,
    mailbox TEXT,
    gmail_message_id TEXT,
    from_addr TEXT,
    from_domain TEXT,
    subject TEXT,
    verdict TEXT,
    score DOUBLE PRECISION,
    label TEXT NOT NULL,
    actor TEXT,
    note TEXT
);
CREATE TABLE IF NOT EXISTS indicators (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_id INTEGER NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    value TEXT NOT NULL,
    weight INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_ind_kind_value ON indicators(kind, value);

CREATE TABLE IF NOT EXISTS campaign_obs (
    dest TEXT NOT NULL PRIMARY KEY,
    message_id TEXT DEFAULT '',
    sender TEXT DEFAULT '',
    mailbox TEXT DEFAULT '',
    subject TEXT DEFAULT '',
    verdict TEXT DEFAULT '',
    threat_class TEXT DEFAULT '',
    seen_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    keys_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_cobs_seen ON campaign_obs(seen_at);

CREATE TABLE IF NOT EXISTS campaigns (
    id TEXT NOT NULL PRIMARY KEY,
    kind TEXT NOT NULL,
    pattern TEXT NOT NULL,
    members INTEGER NOT NULL,
    senders INTEGER NOT NULL,
    mailboxes INTEGER NOT NULL,
    flagged INTEGER NOT NULL,
    first_seen DOUBLE PRECISION NOT NULL,
    last_seen DOUBLE PRECISION NOT NULL,
    keys_json TEXT NOT NULL,
    senders_json TEXT NOT NULL,
    mailboxes_json TEXT NOT NULL,
    dests_json TEXT NOT NULL,
    subjects_json TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    ai_title TEXT NOT NULL DEFAULT '',
    ai_summary TEXT NOT NULL DEFAULT '',
    attack_class TEXT NOT NULL DEFAULT '',
    confidence TEXT NOT NULL DEFAULT '',
    insight_json TEXT NOT NULL DEFAULT '{}',
    facts_hash TEXT NOT NULL DEFAULT '',
    ai_provider TEXT NOT NULL DEFAULT '',
    ai_model TEXT NOT NULL DEFAULT '',
    ai_assessed_at DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cam_last ON campaigns(last_seen);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS ai_title TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS ai_summary TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS attack_class TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS confidence TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS insight_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS facts_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS ai_provider TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS ai_model TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS ai_assessed_at DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS sender_ip_log (
    sender TEXT NOT NULL,
    ip TEXT NOT NULL,
    verdict TEXT DEFAULT '',
    message_id TEXT,
    seen_at DOUBLE PRECISION NOT NULL,
    identity INTEGER DEFAULT 1,
    identity_reason TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_sil_sender ON sender_ip_log(sender);
CREATE INDEX IF NOT EXISTS idx_sil_ip ON sender_ip_log(ip);

CREATE TABLE IF NOT EXISTS ip_shortener_log (
    ip TEXT NOT NULL,
    sender TEXT NOT NULL,
    shortener_domain TEXT NOT NULL,
    verdict TEXT DEFAULT '',
    message_id TEXT,
    seen_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_isl_ip ON ip_shortener_log(ip);
CREATE INDEX IF NOT EXISTS idx_isl_shortener ON ip_shortener_log(shortener_domain);

CREATE TABLE IF NOT EXISTS sender_shortener_log (
    sender TEXT NOT NULL,
    shortener_domain TEXT NOT NULL,
    verdict TEXT DEFAULT '',
    message_id TEXT,
    seen_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ssl_sender ON sender_shortener_log(sender);
CREATE INDEX IF NOT EXISTS idx_ssl_shortener ON sender_shortener_log(shortener_domain);

CREATE TABLE IF NOT EXISTS sender_history (
    sender TEXT NOT NULL,
    seen_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sh_sender ON sender_history(sender);
CREATE INDEX IF NOT EXISTS idx_sh_seen_at ON sender_history(seen_at);

CREATE TABLE IF NOT EXISTS sender_profile_obs (
    sender TEXT NOT NULL,
    asn TEXT DEFAULT '',
    country TEXT DEFAULT '',
    network_role TEXT DEFAULT '',
    vpn INTEGER DEFAULT 0,
    spf TEXT DEFAULT '',
    dkim TEXT DEFAULT '',
    mailbox TEXT DEFAULT '',
    hour_utc INTEGER,
    verdict TEXT DEFAULT '',
    message_id TEXT,
    seen_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_spo_sender ON sender_profile_obs(sender);
CREATE INDEX IF NOT EXISTS idx_spo_seen_at ON sender_profile_obs(seen_at);

CREATE TABLE IF NOT EXISTS recipient_request_log (
    mailbox TEXT NOT NULL,
    sender TEXT NOT NULL,
    request_class TEXT NOT NULL,
    message_id TEXT DEFAULT '',
    seen_at DOUBLE PRECISION NOT NULL,
    UNIQUE(mailbox, sender, request_class, message_id)
);
CREATE INDEX IF NOT EXISTS idx_rrl_mailbox_class ON recipient_request_log(mailbox, request_class);
CREATE INDEX IF NOT EXISTS idx_rrl_mailbox_sender ON recipient_request_log(mailbox, sender);

CREATE TABLE IF NOT EXISTS mail_volume_log (
    sender TEXT NOT NULL,
    mailbox TEXT NOT NULL,
    direction TEXT NOT NULL,
    message_id TEXT DEFAULT '',
    hour_utc INTEGER,
    seen_at DOUBLE PRECISION NOT NULL,
    request_class TEXT DEFAULT '',
    has_attachment INTEGER DEFAULT 0,
    is_reply INTEGER DEFAULT 0,
    UNIQUE(mailbox, message_id)
);
CREATE INDEX IF NOT EXISTS idx_mvl_sender ON mail_volume_log(sender);
CREATE INDEX IF NOT EXISTS idx_mvl_mailbox ON mail_volume_log(mailbox);
CREATE INDEX IF NOT EXISTS idx_mvl_seen_at ON mail_volume_log(seen_at);

CREATE TABLE IF NOT EXISTS correspondence_log (
    actor TEXT NOT NULL,
    peer TEXT NOT NULL,
    direction TEXT NOT NULL,
    request_class TEXT DEFAULT '',
    message_id TEXT DEFAULT '',
    seen_at DOUBLE PRECISION NOT NULL,
    UNIQUE(actor, peer, direction, message_id)
);
CREATE INDEX IF NOT EXISTS idx_cl_actor ON correspondence_log(actor, direction);
CREATE INDEX IF NOT EXISTS idx_cl_peer ON correspondence_log(peer);

CREATE TABLE IF NOT EXISTS worker_locks (
    name TEXT PRIMARY KEY,
    holder TEXT NOT NULL DEFAULT '',
    expires_at DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ai_claims (
    queue_id TEXT PRIMARY KEY,
    claimed_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    claimed_by TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS activity_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL DEFAULT '',
    ts_epoch DOUBLE PRECISION NOT NULL DEFAULT 0,
    action TEXT NOT NULL DEFAULT '',
    actor TEXT NOT NULL DEFAULT '',
    actor_role TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    meta_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_activity_audit_ts ON activity_audit(ts_epoch DESC);

CREATE TABLE IF NOT EXISTS gmail_coverage (
    email TEXT PRIMARY KEY,
    first_seen TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'fanout'
);
CREATE TABLE IF NOT EXISTS gmail_coverage_skipped (
    email TEXT PRIMARY KEY,
    reason TEXT NOT NULL DEFAULT '',
    ts TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS runtime_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL DEFAULT '',
    updated_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_by TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS worker_heartbeats (
    process TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL DEFAULT '{}',
    updated_at DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sender_risk_assess (
    sender TEXT PRIMARY KEY,
    risk TEXT NOT NULL,
    score DOUBLE PRECISION DEFAULT 0,
    posture TEXT DEFAULT '',
    confidence TEXT DEFAULT '',
    summary TEXT DEFAULT '',
    factors TEXT DEFAULT '[]',
    provider TEXT DEFAULT '',
    model_id TEXT DEFAULT '',
    facts_hash TEXT DEFAULT '',
    assessed_at DOUBLE PRECISION NOT NULL DEFAULT 0
);
