#!/usr/bin/env python3
"""Export backend/report.py flag copy into the React console.

Writes web-console/public/flag_descriptions_data.js
(window.SEG_FLAG_DESCRIPTIONS).

Run whenever _FLAG_DESCRIPTIONS / _FLAG_PREFIX_DESCRIPTIONS change:

    python -m cli.build_flag_descriptions
"""
from __future__ import annotations

import json
import sys

from backend import report
from backend.paths import REPO_ROOT


def main() -> int:
    exact = {k: v for k, v in report._FLAG_DESCRIPTIONS.items()}
    prefix = dict(report._FLAG_PREFIX_DESCRIPTIONS)
    payload = {"exact": exact, "prefix": prefix}
    out_path = REPO_ROOT / "web-console" / "public" / "flag_descriptions_data.js"
    payload_js = (
        "// AUTO-GENERATED by python -m cli.build_flag_descriptions — do not edit by hand.\n"
        "// Source: backend/report.py's _FLAG_DESCRIPTIONS / _FLAG_PREFIX_DESCRIPTIONS.\n"
        "window.SEG_FLAG_DESCRIPTIONS = " + json.dumps(payload, indent=2, ensure_ascii=False) + ";\n"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(payload_js, encoding="utf-8")
    print(f"wrote {out_path} — {len(exact)} exact, {len(prefix)} prefix description(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
