"""RSS/Atom source catalogue (FeedSource matrix)."""
from __future__ import annotations

from typing import List

from sentinel.config import (
    CAT_GOV, CAT_VULN, CAT_VENDOR, CAT_SUPPLY, CAT_RESEARCH, CAT_SECTOR, CAT_PH,
    IND_FINTECH, IND_VASP, IND_BANKING, IND_HEALTH, IND_RETAIL, IND_CI, IND_SAAS,
    IND_MFG, IND_GOV, IND_ENERGY, IND_TELCO, IND_EDU, IND_PH,
)
from sentinel.models import FeedSource

FEED_MATRIX: List[FeedSource] = [
    # ---------------- Government & national authorities ----------------
    FeedSource("CISA Advisories (All)", "https://www.cisa.gov/cybersecurity-advisories/all.xml",
               CAT_GOV, 1.35, note="Includes KEV-driven alerts and joint advisories."),
    FeedSource("CISA ICS Advisories", "https://www.cisa.gov/cybersecurity-advisories/ics-advisories.xml",
               CAT_GOV, 1.30, (IND_CI, IND_MFG, IND_ENERGY)),
    FeedSource("NCSC UK Reports", "https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml",
               CAT_GOV, 1.25),
    # NCSC UK (legacy endpoint) removed 2026-07: /api/1/report/rss 404s and NCSC lists no
    # replacement — "NCSC UK Reports" above is the only current feed.
    FeedSource("ACSC Australia Alerts", "https://www.cyber.gov.au/rss/news",
               CAT_GOV, 1.20, note="Sits behind Akamai; times out from some networks even though the URL is correct."),
    # ENISA News removed 2026-07: enisa.europa.eu was redesigned and no longer publishes any
    # RSS feed (all legacy paths 404, no <link rel=alternate> on the site).
    FeedSource("CERT-EU Security Advisories", "https://cert.europa.eu/publications/security-advisories-rss",
               CAT_GOV, 1.20),
    FeedSource("JPCERT/CC Alerts", "https://www.jpcert.or.jp/rss/jpcert.rdf",
               CAT_GOV, 1.10),
    FeedSource("CISA Current Activity", "https://www.cisa.gov/uscert/ncas/current-activity.xml",
               CAT_GOV, 1.25, note="Broader day-to-day CISA feed alongside the advisories feed above."),
    FeedSource("CISA / US-CERT Alerts", "https://www.cisa.gov/uscert/ncas/alerts.xml",
               CAT_GOV, 1.30, note="Classic US-CERT alert stream (TA/AA series)."),
    FeedSource("NCSC UK News", "https://www.ncsc.gov.uk/api/1/services/v1/news-rss-feed.xml",
               CAT_GOV, 1.20),
    FeedSource("CCCS Canada Alerts",
               "https://www.cyber.gc.ca/api/cccs/rss/v1/get?lang=en&cat=alerts",
               CAT_GOV, 1.20),
    FeedSource("CIS Security Advisories", "https://www.cisecurity.org/feed/advisories",
               CAT_GOV, 1.15),
    FeedSource("CIS Security News", "https://www.cisecurity.org/feed",
               CAT_GOV, 1.05),
    FeedSource("CERT-FR (ANSSI) Alerts", "https://www.cert.ssi.gouv.fr/alerte/feed/",
               CAT_GOV, 1.20),
    FeedSource("CERT-FR (ANSSI) Advisories", "https://www.cert.ssi.gouv.fr/avis/feed/",
               CAT_GOV, 1.15),
    FeedSource("BSI Germany (CERT-Bund)", "https://wid.cert-bund.de/content/public/securityAdvisory/rss",
               CAT_GOV, 1.15, note="High volume — hundreds of advisories per pull."),
    FeedSource("Europol Newsroom", "https://www.europol.europa.eu/rss.xml",
               CAT_GOV, 1.05, (IND_FINTECH, IND_BANKING, IND_VASP),
               note="Law-enforcement ops — useful for fraud / ransomware / crypto crime context."),

    # ---------------- Vulnerability databases ----------------
    # NIST NVD RSS feeds removed 2026-07: NIST formally retired XML/RSS in favour of the
    # JSON 2.0 API (services.nvd.nist.gov/rest/json/cves/2.0) — no RSS replacement exists.
    FeedSource("SANS Internet Storm Center", "https://isc.sans.edu/rssfeed_full.xml",
               CAT_VULN, 1.10),
    FeedSource("Zero Day Initiative — Published Advisories", "https://www.zerodayinitiative.com/rss/published/",
               CAT_VULN, 1.20),
    FeedSource("Project Zero", "https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss",
               CAT_VULN, 1.15),
    FeedSource("Exploit-DB", "https://www.exploit-db.com/rss.xml",
               CAT_VULN, 1.10, note="Public exploit / PoC listings — high noise, high early-warning value."),

    # ---------------- Vendor advisories ----------------
    FeedSource("Microsoft Security Update Guide", "https://api.msrc.microsoft.com/update-guide/rss",
               CAT_VENDOR, 1.25),
    # Microsoft MSRC Blog removed 2026-07: msrc.microsoft.com/blog/feed now redirects to a
    # plain HTML page with no feed link; "Microsoft Security Update Guide" above still works.
    FeedSource("Cisco Security Advisories", "https://sec.cloudapps.cisco.com/security/center/psirtrss20/CiscoSecurityAdvisory.xml",
               CAT_VENDOR, 1.25),
    FeedSource("Fortinet FortiGuard PSIRT", "https://filestore.fortinet.com/fortiguard/rss/ir.xml",
               CAT_VENDOR, 1.25),
    FeedSource("AWS Security Bulletins", "https://aws.amazon.com/security/security-bulletins/feed/",
               CAT_VENDOR, 1.25, (IND_SAAS,)),
    FeedSource("Google Cloud Security Bulletins", "https://cloud.google.com/feeds/google-cloud-security-bulletins.xml",
               CAT_VENDOR, 1.25, (IND_SAAS,)),
    FeedSource("Google Workspace Updates", "https://workspaceupdates.googleblog.com/atom.xml",
               CAT_VENDOR, 1.05, (IND_SAAS,)),
    FeedSource("Apple Security Releases", "https://developer.apple.com/news/releases/rss/releases.rss",
               CAT_VENDOR, 1.15),
    FeedSource("Palo Alto Unit 42", "https://unit42.paloaltonetworks.com/feed/",
               CAT_VENDOR, 1.15),
    FeedSource("Cisco Talos Intelligence", "https://blog.talosintelligence.com/rss/",
               CAT_VENDOR, 1.15),
    FeedSource("Google Threat Intelligence (Mandiant)", "https://cloudblog.withgoogle.com/topics/threat-intelligence/rss/",
               CAT_VENDOR, 1.20),
    FeedSource("Rapid7 Blog", "https://blog.rapid7.com/rss/",
               CAT_VENDOR, 1.05),
    FeedSource("Sonatype Blog (Supply Chain)", "https://blog.sonatype.com/rss.xml",
               CAT_VENDOR, 1.10, (IND_SAAS,)),
    FeedSource("Ivanti Security Advisories", "https://www.ivanti.com/blog/topics/security-advisory/rss",
               CAT_VENDOR, 1.20, (IND_SAAS,)),
    FeedSource("Microsoft Security Blog", "https://www.microsoft.com/en-us/security/blog/feed/",
               CAT_VENDOR, 1.20),
    FeedSource("AWS Security Blog", "https://aws.amazon.com/blogs/security/feed/",
               CAT_VENDOR, 1.15, (IND_SAAS,)),
    FeedSource("Okta Security Blog", "https://sec.okta.com/rss.xml",
               CAT_VENDOR, 1.15, (IND_SAAS, IND_FINTECH),
               note="Identity / SSO abuse research — high signal for SaaS and fintech stacks."),
    FeedSource("Proofpoint Threat Insight", "https://www.proofpoint.com/us/rss.xml",
               CAT_VENDOR, 1.10),
    FeedSource("CrowdStrike Blog", "https://www.crowdstrike.com/en-us/blog/feed/",
               CAT_VENDOR, 1.10),
    FeedSource("SentinelOne Blog", "https://www.sentinelone.com/blog/feed/",
               CAT_VENDOR, 1.05),
    FeedSource("Qualys Blog", "https://blog.qualys.com/feed",
               CAT_VENDOR, 1.05),
    FeedSource("Tenable Blog", "https://www.tenable.com/blog/feed",
               CAT_VENDOR, 1.05),
    FeedSource("Bitdefender Labs", "https://www.bitdefender.com/blog/api/rss/labs/",
               CAT_VENDOR, 1.10),

    # ---------------- Supply chain & AppSec ----------------
    FeedSource("Socket.dev Blog", "https://socket.dev/api/blog/feed.atom",
               CAT_SUPPLY, 1.20, (IND_SAAS,),
               note="Malicious npm/PyPI package research and supply-chain IOCs."),
    FeedSource("StepSecurity Blog", "https://www.stepsecurity.io/blog/rss.xml",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="CI/CD and GitHub Actions hardening / supply-chain attacks."),
    FeedSource("SafeDep Blog", "https://safedep.io/rss.xml",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="Open-source dependency risk and malicious package advisories."),
    FeedSource("OX Security", "https://www.ox.security/feed/",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="Application security research and pipeline risk."),
    FeedSource("Aikido Security Blog", "https://www.aikido.dev/blog/rss.xml",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="AppSec, SCA and cloud vulnerability research."),
    FeedSource("Cloudsmith Blog", "https://cloudsmith.com/rss/blog.xml",
               CAT_SUPPLY, 1.10, (IND_SAAS,),
               note="Artifact security, package registries and supply-chain hygiene."),
    FeedSource("Snyk Blog", "https://snyk.io/blog/feed/",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("GitHub Security Blog", "https://github.blog/category/security/feed/",
               CAT_SUPPLY, 1.15, (IND_SAAS,)),
    FeedSource("Chainguard Unchained", "https://www.chainguard.dev/unchained/rss.xml",
               CAT_SUPPLY, 1.10, (IND_SAAS,),
               note="Container / distroless / software supply-chain hardening."),
    FeedSource("PortSwigger Research", "https://www.portswigger.net/research/rss",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="Web AppSec research and novel exploit techniques."),
    FeedSource("Trail of Bits Blog", "https://blog.trailofbits.com/feed/",
               CAT_SUPPLY, 1.15, (IND_SAAS, IND_VASP),
               note="Crypto, compilers, and high-assurance engineering research."),

    # ---------------- Global CTI & research ----------------
    FeedSource("The Hacker News", "https://feeds.feedburner.com/TheHackersNews", CAT_RESEARCH, 1.00,
               note="thehackernews.com/rss.xml now sits behind a Cloudflare JS challenge; this Feedburner mirror bypasses it."),
    FeedSource("BleepingComputer", "https://www.bleepingcomputer.com/feed/", CAT_RESEARCH, 1.05),
    FeedSource("Krebs on Security", "https://krebsonsecurity.com/feed/", CAT_RESEARCH, 1.10,
               (IND_FINTECH, IND_BANKING, IND_RETAIL)),
    FeedSource("Dark Reading", "https://www.darkreading.com/rss.xml", CAT_RESEARCH, 1.00),
    FeedSource("GBHackers", "https://gbhackers.com/feed/", CAT_RESEARCH, 0.95),
    FeedSource("Cyber Security News", "https://cybersecuritynews.com/feed/", CAT_RESEARCH, 1.00),
    FeedSource("Infosecurity Magazine", "https://www.infosecurity-magazine.com/rss/news/",
               CAT_RESEARCH, 1.05),
    FeedSource("SecurityWeek", "https://www.securityweek.com/feed/", CAT_RESEARCH, 1.05),
    FeedSource("Trend Micro Research", "https://feeds.feedburner.com/TrendMicroResearch",
               CAT_RESEARCH, 1.10),
    FeedSource("The Record (Recorded Future)", "https://therecord.media/feed", CAT_RESEARCH, 1.05),
    # Security Intelligence (IBM X-Force) removed 2026-07: securityintelligence.com/feed
    # now redirects to ibm.com/think/security, a plain HTML page — IBM retired RSS when it
    # consolidated blogs into IBM Think.
    FeedSource("Schneier on Security", "https://www.schneier.com/feed/atom/", CAT_RESEARCH, 0.95),
    FeedSource("Securelist (Kaspersky GReAT)", "https://securelist.com/feed/", CAT_RESEARCH, 1.05),
    FeedSource("Securelist — APT", "https://securelist.com/tag/apt/feed/", CAT_RESEARCH, 1.15,
               note="APT-tagged Securelist posts only."),
    FeedSource("Kaspersky Blog", "https://www.kaspersky.com/blog/feed/", CAT_RESEARCH, 0.95),
    FeedSource("WeLiveSecurity (ESET)", "https://www.welivesecurity.com/feed/", CAT_RESEARCH, 1.05),
    FeedSource("ESET Blog (Feedburner)", "https://feeds.feedburner.com/eset/blog", CAT_RESEARCH, 1.00),
    FeedSource("Malwarebytes Labs", "https://blog.malwarebytes.com/feed/", CAT_RESEARCH, 1.00),
    FeedSource("Google Online Security Blog", "https://security.googleblog.com/feeds/posts/default?alt=rss",
               CAT_RESEARCH, 1.05),
    FeedSource("Check Point Research", "https://research.checkpoint.com/feed/", CAT_RESEARCH, 1.10),
    FeedSource("SentinelOne Labs", "https://www.sentinelone.com/labs/feed/", CAT_RESEARCH, 1.10),
    FeedSource("The DFIR Report", "https://thedfirreport.com/feed/", CAT_RESEARCH, 1.15,
               note="Deep incident-response case studies rather than daily news."),
    FeedSource("Huntress Blog", "https://www.huntress.com/blog/rss.xml", CAT_RESEARCH, 1.00,
               note="High volume — includes non-security product posts alongside threat research."),
    FeedSource("Recorded Future Blog", "https://www.recordedfuture.com/feed", CAT_RESEARCH, 1.05),
    FeedSource("Flashpoint Blog", "https://www.flashpoint.io/blog/feed/", CAT_RESEARCH, 1.10),
    FeedSource("EclecticIQ Blog", "https://blog.eclecticiq.com/rss.xml", CAT_RESEARCH, 1.05),
    FeedSource("Elastic Security Labs", "https://www.elastic.co/security-labs/rss/feed.xml",
               CAT_RESEARCH, 1.15),
    FeedSource("Datadog Security Labs", "https://securitylabs.datadoghq.com/rss/feed.xml",
               CAT_RESEARCH, 1.10, (IND_SAAS,)),
    FeedSource("Wiz Research Blog", "https://www.wiz.io/blog/rss.xml",
               CAT_RESEARCH, 1.15, (IND_SAAS,)),
    FeedSource("Cloudflare Security", "https://blog.cloudflare.com/tag/security/rss/",
               CAT_RESEARCH, 1.10, (IND_SAAS,)),
    FeedSource("VirusTotal Blog", "https://blog.virustotal.com/feeds/posts/default?alt=rss",
               CAT_RESEARCH, 1.05),
    FeedSource("Red Canary Blog", "https://redcanary.com/feed/", CAT_RESEARCH, 1.10),
    FeedSource("TrustedSec Blog", "https://www.trustedsec.com/feed/", CAT_RESEARCH, 1.05),
    FeedSource("SpecterOps (Medium)", "https://medium.com/feed/specter-ops-posts",
               CAT_RESEARCH, 1.15, note="AD / tradecraft research (BloodHound ecosystem)."),
    FeedSource("ANY.RUN Blog", "https://any.run/cybersecurity-blog/feed/", CAT_RESEARCH, 1.05),
    FeedSource("MalwareTech Blog", "https://www.malwaretech.com/feed", CAT_RESEARCH, 1.05),
    FeedSource("NVISO Labs", "https://blog.nviso.eu/feed/", CAT_RESEARCH, 1.05),
    FeedSource("Help Net Security", "https://www.helpnetsecurity.com/feed/", CAT_RESEARCH, 1.00),
    FeedSource("Security Affairs", "https://securityaffairs.com/feed", CAT_RESEARCH, 1.00),
    FeedSource("CyberScoop", "https://www.cyberscoop.com/feed/", CAT_RESEARCH, 1.00),
    FeedSource("SC World", "https://www.scworld.com/rss", CAT_RESEARCH, 1.00),
    FeedSource("Threatpost", "https://threatpost.com/feed/", CAT_RESEARCH, 0.95,
               note="Legacy brand still publishing via RSS."),
    FeedSource("Wired — Security", "https://www.wired.com/feed/category/security/latest/rss",
               CAT_RESEARCH, 0.95),
    FeedSource("The Register — Security", "https://www.theregister.com/security/headlines.atom",
               CAT_RESEARCH, 1.00),
    FeedSource("Hackmageddon", "https://www.hackmageddon.com/feed/", CAT_RESEARCH, 0.95,
               note="Monthly cyber-attack timelines / stats."),
    FeedSource("Troy Hunt", "https://www.troyhunt.com/rss/", CAT_RESEARCH, 1.00,
               note="Have I Been Pwned / breach commentary."),
    FeedSource("Graham Cluley", "https://www.grahamcluley.com/feed/", CAT_RESEARCH, 0.95),
    FeedSource("Darknet.org.uk", "https://www.darknet.org.uk/feed/", CAT_RESEARCH, 0.90),
    FeedSource("Hack The Box Blog", "https://www.hackthebox.com/blog/rss.xml", CAT_RESEARCH, 0.90),
    FeedSource("Security.nl Headlines", "https://www.security.nl/rss/headlines.xml",
               CAT_RESEARCH, 0.95),
    # Reddit Atom feeds work, but Reddit rate-limits aggressively (HTTP 429) if pulled in
    # parallel. fetch_sources() serialises these URLs and retries with backoff.
    FeedSource("Reddit r/netsec", "https://www.reddit.com/r/netsec/.rss?limit=25",
               CAT_RESEARCH, 0.90,
               note="Atom feed (~25 posts). Fetched serially to avoid Reddit 429s."),
    FeedSource("Reddit r/cybersecurity",
               "https://www.reddit.com/r/cybersecurity/.rss?limit=25",
               CAT_RESEARCH, 0.85,
               note="Large subreddit — often 429s if hammered; serial fetch + backoff applied."),
    FeedSource("Reddit r/blueteamsec",
               "https://www.reddit.com/r/blueteamsec/.rss?limit=25",
               CAT_RESEARCH, 0.95,
               note="Blue-team oriented community signal (~25 Atom entries when not rate-limited)."),
    FeedSource("Reddit r/dfir", "https://www.reddit.com/r/dfir/.rss?limit=25",
               CAT_RESEARCH, 0.90, note="Digital forensics / IR community."),
    FeedSource("Reddit r/Malware", "https://www.reddit.com/r/Malware/.rss?limit=25",
               CAT_RESEARCH, 0.90),
    FeedSource("Reddit r/AskNetsec", "https://www.reddit.com/r/AskNetsec/.rss?limit=25",
               CAT_RESEARCH, 0.80),
    FeedSource("Reddit r/ReverseEngineering",
               "https://www.reddit.com/r/ReverseEngineering/.rss?limit=25",
               CAT_RESEARCH, 0.85),
    FeedSource("Reddit r/InfoSecNews", "https://www.reddit.com/r/InfoSecNews/.rss?limit=25",
               CAT_RESEARCH, 0.85),

    # ---------------- Sector-specific ----------------
    FeedSource("BankInfoSecurity", "https://www.bankinfosecurity.com/rss-feeds",
               CAT_SECTOR, 1.20, (IND_FINTECH, IND_BANKING, IND_VASP),
               note="Whole domain sits behind a Cloudflare JS challenge; no mirror found (unlike Hacker News)."),
    # HHS HC3 / Health Sector Alerts removed 2026-07: hhs.gov/sites/default/files/hc3-rss.xml
    # 403s and no RSS successor exists — HHS HC3 now only distributes via email listserv.
    # Healthcare IT News removed 2026-07: /home/feed is behind a Cloudflare bot challenge
    # that blocks even browser-UA requests; no alternate feed path found.
    FeedSource("HIPAA Journal", "https://www.hipaajournal.com/feed/",
               CAT_SECTOR, 1.15, (IND_HEALTH,)),
    FeedSource("Chainalysis Blog", "https://www.chainalysis.com/feed/",
               CAT_SECTOR, 1.15, (IND_VASP,)),
    FeedSource("TRM Labs Blog", "https://www.trmlabs.com/post/rss.xml",
               CAT_SECTOR, 1.15, (IND_VASP,)),
    FeedSource("CoinDesk", "https://www.coindesk.com/arc/outboundfeeds/rss/",
               CAT_SECTOR, 1.05, (IND_VASP,),
               note="Crypto market + exchange/hack coverage — filter via VASP keywords."),
    FeedSource("Cointelegraph", "https://cointelegraph.com/rss",
               CAT_SECTOR, 1.00, (IND_VASP,)),
    FeedSource("SlowMist (Medium)", "https://slowmist.medium.com/feed",
               CAT_SECTOR, 1.20, (IND_VASP,),
               note="Blockchain security / exchange incident write-ups."),
    # Elliptic Blog removed 2026-07: elliptic.co migrated to a Nuxt SPA under /insights and
    # no longer publishes any RSS/Atom feed (confirmed no <link rel=alternate>).
    # Dragos Blog (OT/ICS) removed 2026-07: their own declared feed URL
    # (dragos.com/blog.rss) returns HTTP 200/202 with an empty body — feed generator appears
    # broken server-side. Re-add if they fix it; no working alternative exists today.
    FeedSource("Industrial Cyber", "https://industrialcyber.co/feed/",
               CAT_SECTOR, 1.05, (IND_CI, IND_ENERGY, IND_MFG)),
    FeedSource("Retail & Hospitality ISAC News", "https://rhisac.org/feed/",
               CAT_SECTOR, 1.15, (IND_RETAIL,)),

    # ---------------- Philippines — FinTech, fraud & cyber ----------------
    # No PH regulator/law-enforcement RSS survived testing (BSP, SEC PH, DICT, NCERT/CERT-PH
    # and PNP Anti-Cybercrime Group all 403/404/SSL-fail as of 2026-07 — none publish RSS
    # publicly, or actively block non-browser requests). National Privacy Commission is the
    # one official source that works. The rest are national outlets whose crime/business/tech
    # desks reliably cover e-wallet fraud, fake IDs, financial scams and local cyber incidents
    # — the app's own keyword/industry scoring (see "Philippines — E-Wallets, IDs & Fraud"
    # profile) is what filters signal from the general news noise.
    FeedSource("National Privacy Commission (PH)", "https://privacy.gov.ph/feed/",
               CAT_PH, 1.30, (IND_PH, IND_FINTECH, IND_BANKING),
               note="Official PH data breach notifications and privacy advisories."),
    FeedSource("Rappler — Nation", "https://www.rappler.com/nation/feed/",
               CAT_PH, 1.10, (IND_PH,)),
    FeedSource("Rappler — Philippines", "https://www.rappler.com/philippines/feed/",
               CAT_PH, 1.10, (IND_PH,)),
    FeedSource("Rappler — Technology", "https://www.rappler.com/technology/feed/",
               CAT_PH, 1.10, (IND_PH,)),
    FeedSource("Rappler — Business", "https://www.rappler.com/business/feed/",
               CAT_PH, 1.10, (IND_PH, IND_FINTECH, IND_BANKING, IND_VASP)),
    FeedSource("Philstar — Headlines", "https://www.philstar.com/rss/headlines",
               CAT_PH, 1.00, (IND_PH,)),
    FeedSource("Philstar — Nation", "https://www.philstar.com/rss/nation",
               CAT_PH, 1.00, (IND_PH,)),
    FeedSource("Philstar — Business", "https://www.philstar.com/rss/business",
               CAT_PH, 1.05, (IND_PH, IND_FINTECH, IND_BANKING, IND_VASP)),
    FeedSource("BusinessWorld (PH)", "https://www.bworldonline.com/feed/",
               CAT_PH, 1.10, (IND_PH, IND_FINTECH, IND_BANKING)),
    FeedSource("BusinessWorld — Banking & Finance",
               "https://www.bworldonline.com/category/banking-finance/feed/",
               CAT_PH, 1.15, (IND_PH, IND_FINTECH, IND_BANKING, IND_VASP)),
    FeedSource("BusinessWorld — Technology",
               "https://www.bworldonline.com/category/technology/feed/",
               CAT_PH, 1.10, (IND_PH, IND_SAAS)),
    FeedSource("Inquirer — Newsinfo", "https://newsinfo.inquirer.net/feed",
               CAT_PH, 1.00, (IND_PH,)),
    FeedSource("Inquirer — Business", "https://business.inquirer.net/feed",
               CAT_PH, 1.05, (IND_PH, IND_FINTECH, IND_BANKING, IND_VASP)),
    FeedSource("Inquirer — Technology", "https://technology.inquirer.net/feed",
               CAT_PH, 1.05, (IND_PH,)),

    # ---------------- Expanded 2026-08 (live-probed) ----------------
    FeedSource("CCCS Canada Advisories",
               "https://www.cyber.gc.ca/api/cccs/rss/v1/get?lang=en&cat=advisories",
               CAT_GOV, 1.20),
    FeedSource("CCCS Canada News",
               "https://www.cyber.gc.ca/api/cccs/rss/v1/get?lang=en&cat=news",
               CAT_GOV, 1.10),
    FeedSource("JPCERT/CC English", "https://www.jpcert.or.jp/english/rss/jpcert-en.rdf",
               CAT_GOV, 1.10),
    FeedSource("JPCERT/CC Blog (EN)", "https://blogs.jpcert.or.jp/en/atom.xml",
               CAT_GOV, 1.10),
    FeedSource("JVN (English)", "https://jvn.jp/en/rss/jvn.rdf",
               CAT_VULN, 1.15),
    FeedSource("Zero Day Initiative — Upcoming", "https://www.zerodayinitiative.com/rss/upcoming/",
               CAT_VULN, 1.15, note="Pre-disclosure / upcoming ZDI advisories."),
    FeedSource("VulDB Recent", "https://vuldb.com/?rss.recent",
               CAT_VULN, 1.05, note="High volume vulnerability database feed."),
    FeedSource("Full Disclosure (SecLists)", "https://seclists.org/rss/fulldisclosure.rss",
               CAT_VULN, 1.05),
    FeedSource("Sophos Security Advisories", "https://www.sophos.com/en-us/security-advisories/feed",
               CAT_VENDOR, 1.15),
    FeedSource("Check Point Blog", "https://blog.checkpoint.com/feed/",
               CAT_VENDOR, 1.05),
    FeedSource("Check Point Threat Research",
               "https://research.checkpoint.com/category/threat-research/feed/",
               CAT_VENDOR, 1.15),
    FeedSource("Trend Micro Simply Security", "https://feeds.feedburner.com/TrendMicroSimplySecurity",
               CAT_VENDOR, 1.00),
    FeedSource("FortiGuard Outbreak Alerts",
               "https://filestore.fortinet.com/fortiguard/rss/outbreak.xml",
               CAT_VENDOR, 1.20),
    FeedSource("FortiGuard Threat Signal",
               "https://filestore.fortinet.com/fortiguard/rss/threat-signal-report.xml",
               CAT_VENDOR, 1.15),
    FeedSource("Ivanti Blog", "https://www.ivanti.com/blog/rss",
               CAT_VENDOR, 1.05, (IND_SAAS,)),
    FeedSource("Google Safety & Security", "https://blog.google/technology/safety-security/rss/",
               CAT_VENDOR, 1.05),
    FeedSource("KnowBe4 Blog", "https://blog.knowbe4.com/rss.xml",
               CAT_VENDOR, 1.00, note="Phishing / security awareness — useful for human-risk signals."),
    FeedSource("1Password Blog", "https://blog.1password.com/index.xml",
               CAT_VENDOR, 1.00, (IND_SAAS,)),
    FeedSource("Aqua Security Blog", "https://blog.aquasec.com/rss.xml",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("Sysdig Blog", "https://www.sysdig.com/blog/rss.xml",
               CAT_SUPPLY, 1.05, (IND_SAAS,)),
    FeedSource("Orca Security Blog", "https://orca.security/resources/blog/feed/",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("JFrog Security Blog", "https://jfrog.com/blog/category/security/feed/",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("Endor Labs Blog", "https://www.endorlabs.com/blog/rss.xml",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("Legit Security Blog", "https://www.legitsecurity.com/blog/rss.xml",
               CAT_SUPPLY, 1.05, (IND_SAAS,)),
    FeedSource("OpenSSF Blog", "https://openssf.org/feed/",
               CAT_SUPPLY, 1.10, (IND_SAAS,)),
    FeedSource("ProjectDiscovery Blog", "https://blog.projectdiscovery.io/rss/",
               CAT_SUPPLY, 1.15, (IND_SAAS,),
               note="Nuclei / attack-surface research."),
    FeedSource("Assetnote Research", "https://blog.assetnote.io/feed.xml",
               CAT_SUPPLY, 1.15, (IND_SAAS,)),
    FeedSource("Detectify Blog", "https://blog.detectify.com/feed/",
               CAT_SUPPLY, 1.05, (IND_SAAS,)),
    FeedSource("Intruder Blog", "https://www.intruder.io/blog/rss.xml",
               CAT_SUPPLY, 1.05, (IND_SAAS,)),
    FeedSource("Horizon3.ai", "https://www.horizon3.ai/feed/",
               CAT_SUPPLY, 1.10, (IND_SAAS,),
               note="Assumed-breach / NodeZero offensive research."),
    FeedSource("Quarkslab Blog", "https://blog.quarkslab.com/feeds/all.atom.xml",
               CAT_RESEARCH, 1.15),
    FeedSource("Malware Traffic Analysis",
               "https://www.malware-traffic-analysis.net/blog-entries.rss",
               CAT_RESEARCH, 1.15, note="PCAP / traffic-based malware case studies."),
    FeedSource("Didier Stevens", "https://blog.didierstevens.com/feed/",
               CAT_RESEARCH, 1.10),
    FeedSource("Hexacorn", "https://www.hexacorn.com/blog/feed/",
               CAT_RESEARCH, 1.05),
    FeedSource("Osanda Malith", "https://osandamalith.com/feed/",
               CAT_RESEARCH, 1.00),
    FeedSource("Intigriti Blog", "https://blog.intigriti.com/feed/",
               CAT_RESEARCH, 1.05, note="Bug-bounty / web research."),
    FeedSource("UnderCode News", "https://undercodenews.com/feed/",
               CAT_RESEARCH, 0.95),
    FeedSource("Security Newspaper", "https://www.securitynewspaper.com/feed/",
               CAT_RESEARCH, 0.95),
    FeedSource("ZDNet Security", "https://www.zdnet.com/topic/security/rss.xml",
               CAT_RESEARCH, 0.95),
    FeedSource("CSO Online", "https://www.csoonline.com/feed/",
               CAT_RESEARCH, 1.00),
    FeedSource("Computerworld", "https://www.computerworld.com/feed/",
               CAT_RESEARCH, 0.90),
    FeedSource("InfoWorld", "https://www.infoworld.com/feed",
               CAT_RESEARCH, 0.90),
    FeedSource("Network World", "https://www.networkworld.com/feed",
               CAT_RESEARCH, 0.90),
    FeedSource("BBC Technology", "https://feeds.bbci.co.uk/news/technology/rss.xml",
               CAT_RESEARCH, 0.85),
    FeedSource("NYTimes Technology", "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
               CAT_RESEARCH, 0.85),
    FeedSource("Guardian — Computer Security",
               "https://www.theguardian.com/technology/data-computer-security/rss",
               CAT_RESEARCH, 0.95),
    FeedSource("Decrypt", "https://decrypt.co/feed",
               CAT_SECTOR, 1.00, (IND_VASP,)),
    FeedSource("The Block", "https://www.theblock.co/rss.xml",
               CAT_SECTOR, 1.05, (IND_VASP,)),
    FeedSource("Bitcoin Magazine", "https://bitcoinmagazine.com/.rss/full/",
               CAT_SECTOR, 0.95, (IND_VASP,)),
    FeedSource("Chainalysis Reports", "https://blog.chainalysis.com/reports/feed/",
               CAT_SECTOR, 1.15, (IND_VASP,)),
    FeedSource("BlockSec (Medium)", "https://blocksecteam.medium.com/feed",
               CAT_SECTOR, 1.15, (IND_VASP,)),
    FeedSource("PeckShield (Medium)", "https://peckshield.medium.com/feed",
               CAT_SECTOR, 1.15, (IND_VASP,)),
    FeedSource("CertiK (Medium)", "https://certik.medium.com/feed",
               CAT_SECTOR, 1.10, (IND_VASP,)),
    FeedSource("Immunefi Blog", "https://immunefi.com/blog/rss/",
               CAT_SECTOR, 1.15, (IND_VASP,),
               note="Web3 bug-bounty / exploit disclosures."),
    FeedSource("Web3 Is Going Great", "https://www.web3isgoinggreat.com/feed.xml",
               CAT_SECTOR, 1.05, (IND_VASP,),
               note="Curated crypto scam / hack timeline."),
    FeedSource("RugDoc", "https://rugdoc.io/feed/",
               CAT_SECTOR, 1.00, (IND_VASP,)),

    # ---------------- Expansion wave (verified live RSS/Atom, 2026-08) ----------------
    # Government / CERT
    FeedSource("CIRCL Luxembourg", "https://www.circl.lu/atom.xml",
               CAT_GOV, 1.15, note="LU national CERT — malware / incident reports."),
    FeedSource("H-ISAC News", "https://h-isac.org/feed/",
               CAT_SECTOR, 1.10, (IND_HEALTH,),
               note="Health-ISAC member news and sector alerts."),

    # OS / browser / vendor advisories
    FeedSource("Ubuntu Security Notices", "https://ubuntu.com/security/notices/rss.xml",
               CAT_VULN, 1.15),
    FeedSource("Palo Alto Networks Advisories", "https://security.paloaltonetworks.com/rss.xml",
               CAT_VENDOR, 1.20),
    FeedSource("Microsoft Threat Intelligence",
               "https://www.microsoft.com/en-us/security/blog/topic/threat-intelligence/feed/",
               CAT_VENDOR, 1.20),
    FeedSource("Mozilla Security Blog", "https://blog.mozilla.org/security/feed/",
               CAT_VENDOR, 1.10),
    FeedSource("Red Hat Security Blog", "https://www.redhat.com/en/rss/blog/channel/security",
               CAT_VENDOR, 1.10),
    FeedSource("Chromium Releases", "https://chromereleases.googleblog.com/feeds/posts/default",
               CAT_VENDOR, 1.05, note="Chrome/Chromium release channel — security fixes often land here first."),
    FeedSource("Netskope Blog", "https://www.netskope.com/blog/feed",
               CAT_VENDOR, 1.05, (IND_SAAS,)),

    # Threat intel platforms / researchers
    FeedSource("MITRE ATT&CK Blog", "https://medium.com/feed/mitre-attack",
               CAT_RESEARCH, 1.15),
    FeedSource("MISP Project", "https://www.misp-project.org/feed.xml",
               CAT_RESEARCH, 1.10, note="Open-source CTI platform releases & community intel."),
    FeedSource("GreyNoise Blog", "https://www.greynoise.io/blog/rss.xml",
               CAT_RESEARCH, 1.10),
    FeedSource("Shodan Blog", "https://blog.shodan.io/rss/",
               CAT_RESEARCH, 1.05),
    FeedSource("Censys Blog", "https://censys.com/feed/",
               CAT_RESEARCH, 1.05),
    FeedSource("Team Cymru Blog", "https://www.team-cymru.com/post/rss.xml",
               CAT_RESEARCH, 1.10),
    FeedSource("Pulsedive Blog", "https://blog.pulsedive.com/rss/",
               CAT_RESEARCH, 1.05),
    FeedSource("Group-IB Medium", "https://group-ib.medium.com/feed",
               CAT_RESEARCH, 1.15),
    FeedSource("Objective-See", "https://objective-see.org/rss.xml",
               CAT_RESEARCH, 1.10, note="macOS malware research (Patrick Wardle)."),
    FeedSource("MalwareJake", "https://malwarejake.blogspot.com/feeds/posts/default",
               CAT_RESEARCH, 1.00),
    FeedSource("Cybereason Blog", "https://www.cybereason.com/blog/rss.xml",
               CAT_RESEARCH, 1.05),
    FeedSource("Avast Blog", "https://blog.avast.com/rss.xml",
               CAT_RESEARCH, 1.00),
    FeedSource("Forensic Focus", "https://www.forensicfocus.com/feed/",
               CAT_RESEARCH, 1.05),
    FeedSource("SANS ISC Diary", "https://isc.sans.edu/rssfeed.xml",
               CAT_VULN, 1.10, note="Handler diary companion to the full ISC feed."),

    # Ransomware / breach / malware deep-dives
    FeedSource("Ransomware.live", "https://ransomware.live/rss.xml",
               CAT_RESEARCH, 1.15, note="Aggregated ransomware group leak-site activity."),
    FeedSource("DataBreaches.net", "https://www.databreaches.net/feed/",
               CAT_RESEARCH, 1.05),
    FeedSource("Securelist — Malware", "https://securelist.com/tag/malware/feed/",
               CAT_RESEARCH, 1.10),
    FeedSource("Securelist — Ransomware", "https://securelist.com/tag/ransomware/feed/",
               CAT_RESEARCH, 1.15),
    FeedSource("Security Affairs — APT", "https://securityaffairs.com/category/apt/feed",
               CAT_RESEARCH, 1.10),
    FeedSource("Security Affairs — Malware", "https://securityaffairs.com/category/malware/feed",
               CAT_RESEARCH, 1.05),
    FeedSource("GBHackers — Malware", "https://gbhackers.com/category/malware/feed/",
               CAT_RESEARCH, 0.95),
    FeedSource("Cyber Security News — APT", "https://cybersecuritynews.com/category/apt/feed/",
               CAT_RESEARCH, 1.00),
    FeedSource("Threatpost — Vulnerabilities", "https://threatpost.com/category/vulnerabilities/feed/",
               CAT_RESEARCH, 0.95),
    FeedSource("Help Net Security — Threats", "https://www.helpnetsecurity.com/tag/threats/feed/",
               CAT_RESEARCH, 1.00),
    FeedSource("Red Canary Blog (alt)", "https://redcanary.com/blog/feed/",
               CAT_RESEARCH, 1.10),

    # News desks
    FeedSource("Cybersecurity Dive", "https://www.cybersecuritydive.com/feeds/news/",
               CAT_RESEARCH, 1.05),
    FeedSource("TechCrunch Security", "https://techcrunch.com/category/security/feed/",
               CAT_RESEARCH, 0.95),
    FeedSource("SecurityBrief Australia", "https://securitybrief.com.au/feed",
               CAT_RESEARCH, 0.95),

    # Community
    FeedSource("Reddit r/netsecstudents",
               "https://www.reddit.com/r/netsecstudents/.rss?limit=25",
               CAT_RESEARCH, 0.90, note="Learner / blue-team discussion — lower authority."),
    FeedSource("Reddit r/ThreatIntel",
               "https://www.reddit.com/r/ThreatIntel/.rss?limit=25",
               CAT_RESEARCH, 0.95, note="Community CTI shares; may 429 under load."),
    FeedSource("Reddit r/cybercrime",
               "https://www.reddit.com/r/cybercrime/.rss?limit=25",
               CAT_RESEARCH, 0.95),
]

