#!/usr/bin/env python3
"""Exports app/report.py's _FLAG_DESCRIPTIONS / _FLAG_PREFIX_DESCRIPTIONS into
a JS data file the dashboard can load
(dashboard/flag_descriptions_data.js -> window.SEG_FLAG_DESCRIPTIONS).

index.html previously hand-maintained its own copy of these two dicts
(FLAG_DESC / FLAG_PREFIX_DESC), duplicated from report.py by hand — a real
drift risk every time a new flag is added to one but not the other (this is
exactly what happened across Phases 1-5 of the TMES policy-parity plan: none
of forensics_*/spoofed_attachment_type/double_extension_executable/
correlation_seen_before/bulk_sender_no_unsubscribe/domain_age_low had a
dashboard description until this script existed). index.html's describeFlag()
now prefers this exported data, falling back to its own small hardcoded copy
only if this file failed to load.

Run whenever app/report.py's flag descriptions change:
    python3 dashboard/build_flag_descriptions.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from app import report  # noqa: E402


def main() -> int:
    out_path = Path(__file__).resolve().parent / "flag_descriptions_data.js"

    # "policy_suppressed:" is deliberately excluded — its description is
    # built dynamically in report.py (category name + the underlying flag's
    # own description), not a static template; the dashboard's describeFlag()
    # keeps its own small equivalent for that one case.
    exact = {k: v for k, v in report._FLAG_DESCRIPTIONS.items()}
    prefix = dict(report._FLAG_PREFIX_DESCRIPTIONS)

    payload = {"exact": exact, "prefix": prefix}

    out_path.write_text(
        "// AUTO-GENERATED by dashboard/build_flag_descriptions.py — do not edit by hand.\n"
        "// Source: app/report.py's _FLAG_DESCRIPTIONS / _FLAG_PREFIX_DESCRIPTIONS.\n"
        "window.SEG_FLAG_DESCRIPTIONS = " + json.dumps(payload, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path} — {len(exact)} exact, {len(prefix)} prefix description(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
