// AUTO-GENERATED by dashboard/build_samples_data.py — do not edit by hand.
// Source: samples_output/*.md (eml_analysis_agent.py reports).
window.PDAX_SAMPLES = [
  {
    "source_file": "AWS Notification.eml",
    "risk_level": "HIGH",
    "risk_score": 85,
    "indicators": [
      "sender_domain_mismatch",
      "reply_to_mismatch",
      "brand_impersonation",
      "dmarc_fail",
      "suspicious_link_domain"
    ],
    "warning": "",
    "metadata": {
      "subject": "AWS Notification – S3 Bucket Review Requested | Ref AUP-2026-0407-61038",
      "from": "'AWS Notice' via DevOps Team <devops@pdax.ph>",
      "to": "devops@pdax.ph",
      "cc": "",
      "reply_to": "AWS Notice <noreply@cloud-abuse.org>",
      "date": "Mon, 18 May 2026 20:07:06 +0000",
      "message_id": "<PY0unbISKllUzdr5in4aUr7LkIf0oyFuvzOm@cloud-abuse.org>"
    },
    "auth": {
      "originating_ip": "18.208.22.151",
      "spf": "PASS",
      "dkim": "PASS",
      "address_mismatch": true,
      "mismatch_details": "From domain (pdax.ph) and Reply-To domain (cloud-abuse.org) do not match the impersonated brand (AWS/Amazon). DMARC failed (dara=fail)."
    },
    "content": {
      "summary": "This email impersonates AWS, claiming that a compliance check flagged a publicly accessible S3 bucket and requesting the recipient to review the case.",
      "category": "Phishing",
      "sentiment": "Urgent",
      "entities": {
        "people": [],
        "organizations": [
          "AWS",
          "DevOps Team"
        ],
        "dates_mentioned": [
          "Mon",
          "18 May 2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Review Case"
      ]
    },
    "suspicious_urls": [
      {
        "display_text": "Review Case",
        "actual_url": "https://post.spmailtechnolo.com/f/a/mH2u5d2KXXtWeMEGuOw3pA~~/AAPxGRA~/gUh77TCJb6edlHj71NNxPbknGppdsvFyYVswdNbtG9N8g1n_YFEnuuv_DJYf1OHxOGeEHsWf_F3ixTugiM0BdcH4gDLTSfLe-H_cHZ7oeFX0nW3Om0QLB1Ld1F5geHJJoku7WUX8e8N3ttvedC8WWg~~",
        "mismatch": false
      }
    ],
    "attachments": []
  },
  {
    "source_file": "Booking Confirmation - Sofitel Dubai The Palm - 22 July 2026.eml",
    "risk_level": "HIGH",
    "risk_score": 85,
    "indicators": [
      "DKIM body hash verification failed (neutral status)",
      "From/Return-Path domain mismatch (accor.com vs email.recurly.com)",
      "Action button uses URL shortener (zpr.io) instead of official brand domain"
    ],
    "warning": "",
    "metadata": {
      "subject": "Booking Confirmation - Sofitel Dubai The Palm - 22 July 2026",
      "from": "Hotels@accor.com",
      "to": "dana.bernardo@pdax.ph",
      "cc": "",
      "reply_to": "",
      "date": "Mon, 11 May 2026 00:23:20 +0000",
      "message_id": "<6a01217882be_1282524823765715d@emaily-consumer-7f4ff5dfc4-xx6bc.mail>"
    },
    "auth": {
      "originating_ip": "167.89.104.131",
      "spf": "PASS",
      "dkim": "NEUTRAL",
      "address_mismatch": true,
      "mismatch_details": "From address 'Hotels@accor.com' does not match Return-Path 'email.recurly.com'."
    },
    "content": {
      "summary": "This email purports to be a booking confirmation for Sofitel Dubai The Palm on July 22, 2026, and prompts the recipient to manage their reservation via a hyperlink.",
      "category": "Phishing",
      "sentiment": "Professional",
      "entities": {
        "people": [],
        "organizations": [
          "Sofitel Dubai The Palm",
          "Accor"
        ],
        "dates_mentioned": [
          "22 July 2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Click 'MANAGE MY BOOKING' link"
      ]
    },
    "suspicious_urls": [
      {
        "display_text": "MANAGE MY BOOKING",
        "actual_url": "https://zpr.io/RTeZsLih2ree",
        "mismatch": false
      }
    ],
    "attachments": []
  },
  {
    "source_file": "City Ads Updated Collaterals.eml",
    "risk_level": "HIGH",
    "risk_score": 85,
    "indicators": [
      "header_from_mismatch",
      "generic_greeting",
      "url_shortener",
      "suspicious_return_path"
    ],
    "warning": "",
    "metadata": {
      "subject": "City Ads: Updated Collaterals",
      "from": "Lavinia <laviniabusa.cityads@gmail.com>",
      "to": "Lavinia <laviniabusa.cityads@gmail.com>",
      "cc": "",
      "reply_to": "",
      "date": "Tue, 26 May 2026 08:54:46 +0800",
      "message_id": "<CABoAGBrm7y2Jb3g+wCHK=fKiCg71+fEsLd0sPwtgTGJhLvffzg@mail.gmail.com>"
    },
    "auth": {
      "originating_ip": "18.208.22.144",
      "spf": "PASS",
      "dkim": "PASS",
      "address_mismatch": true,
      "mismatch_details": "From header domain (gmail.com) does not match Return-Path/DKIM signing domain (pdax.ph)."
    },
    "content": {
      "summary": "The email, claiming to be from Lavinia Busa of City Advertising Ventures, sends a generic greeting and a link to 'updated collaterals' hosted on a URL shortener.",
      "category": "Phishing / Business Email Compromise",
      "sentiment": "Neutral",
      "entities": {
        "people": [
          "Lavinia Busa"
        ],
        "organizations": [
          "City Advertising Ventures Corporation"
        ],
        "dates_mentioned": [],
        "amounts_mentioned": []
      },
      "action_items": [
        "Review the provided link for updated collaterals."
      ]
    },
    "suspicious_urls": [
      {
        "display_text": "https://canva.link/0zb5h4jda0cgjnn",
        "actual_url": "https://canva.link/0zb5h4jda0cgjnn",
        "mismatch": false
      }
    ],
    "attachments": []
  },
  {
    "source_file": "Claire Morgan.eml",
    "risk_level": "HIGH",
    "risk_score": 85,
    "indicators": [
      "spf_softfail",
      "dkim_neutral",
      "display_name_mismatch",
      "url_shortener",
      "copyright_complaint_lure"
    ],
    "warning": "",
    "metadata": {
      "subject": "Notice regarding the unauthorized use of Claire Morgan's video/image content – Please see attached details.",
      "from": "Claire Morgan <george.kidunda25@mustudent.ac.tz>",
      "to": "support@pdax.ph",
      "cc": "",
      "reply_to": "",
      "date": "Mon, 25 May 2026 18:27:25 -0700",
      "message_id": "<6a14f6fd.1173ae6c.832d1.de4e@mx.google.com>"
    },
    "auth": {
      "originating_ip": "209.85.210.193",
      "spf": "FAIL",
      "dkim": "NEUTRAL",
      "address_mismatch": true,
      "mismatch_details": "Display name 'Claire Morgan' does not match the mailbox owner 'george.kidunda25' in the From address."
    },
    "content": {
      "summary": "The sender, claiming to be Claire Morgan, alleges unauthorized use of her video or image content in the recipient's advertising materials and requests a review of the details via a provided link.",
      "category": "Phishing / Copyright Claim",
      "sentiment": "Urgent / Formal",
      "entities": {
        "people": [
          "Claire Morgan",
          "George Kidunda"
        ],
        "organizations": [
          "mustudent.ac.tz",
          "pdax.ph"
        ],
        "dates_mentioned": [
          "Mon",
          "25 May 2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Review content usage details via provided link"
      ]
    },
    "suspicious_urls": [
      {
        "display_text": "View content usage details",
        "actual_url": "https://tr.ee/ClaireMorganCF",
        "mismatch": false
      }
    ],
    "attachments": []
  },
  {
    "source_file": "Burpsuite Proposal.eml",
    "risk_level": "MEDIUM",
    "risk_score": 60,
    "indicators": [
      "SPF Softfail",
      "DKIM Not Present",
      "ARC Failure",
      "High Entropy PDF Attachment",
      "Generic Greeting"
    ],
    "warning": "",
    "metadata": {
      "subject": "Burpsuite Proposal",
      "from": "Irene Piodo <ipiodo@armadalabs.tech>",
      "to": "armanandrea <arman.andrea@pdax.ph>",
      "cc": "Dean Armada <darmada@armadalabs.tech>",
      "reply_to": "",
      "date": "Thu, 26 Mar 2026 15:38:48 +0800",
      "message_id": "<19d2914e6ce.3d6c1dbd601734.8119890756353154100@armadalabs.tech>"
    },
    "auth": {
      "originating_ip": "136.143.188.52",
      "spf": "softfail",
      "dkim": "NONE",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "The email is a business proposal from Irene Piodo of Armada Innovation Labs regarding Burpsuite services, addressed to Arman Andrea. It requests the recipient to review the attached PDF proposal.",
      "category": "Business / Sales",
      "sentiment": "Professional",
      "entities": {
        "people": [
          "Irene Legaspi-Piodo",
          "Dean Armada",
          "Arman Andrea"
        ],
        "organizations": [
          "Armada Innovation Labs",
          "PDAX"
        ],
        "dates_mentioned": [
          "Thu",
          "26 Mar 2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Review the attached Burpsuite Proposal PDF"
      ]
    },
    "suspicious_urls": [],
    "attachments": [
      {
        "filename": "1732891814679011_1226335963.png",
        "type": "png",
        "sha256": "c87a2d6e1a30acd5…",
        "flagged": false,
        "reason": "allow"
      },
      {
        "filename": "1732891814707029_1226335963.png",
        "type": "png",
        "sha256": "ec3041ec30929150…",
        "flagged": false,
        "reason": "allow"
      },
      {
        "filename": "1732891814729026_1226335963.png",
        "type": "png",
        "sha256": "6bce57ceff31b99f…",
        "flagged": false,
        "reason": "allow"
      },
      {
        "filename": "1732891814755000_1226335963.png",
        "type": "png",
        "sha256": "7dac9f151f19715c…",
        "flagged": false,
        "reason": "allow"
      },
      {
        "filename": "AILABS_PDAX_BURPSUITE_PROPOSAL_032626.pdf",
        "type": "pdf",
        "sha256": "8df671d5de7acc14…",
        "flagged": false,
        "reason": "sandbox_detonation"
      }
    ]
  },
  {
    "source_file": "Boost Code Quality Now, Pdax.EML",
    "risk_level": "MEDIUM",
    "risk_score": 50,
    "indicators": [
      "dkim_body_hash_mismatch"
    ],
    "warning": "",
    "metadata": {
      "subject": "RE: Boost Code Quality Now, Pdax",
      "from": "Maria Filipe <maria@sales.codacy.com>",
      "to": "Daniel Tiongco <daniel.tiongco@pdax.ph>",
      "cc": "",
      "reply_to": "",
      "date": "Fri, 17 Apr 2026 08:31:34 +0000",
      "message_id": "<MSGAF57F8E8E6284267BEF463CBB9075E51639120100153731444@sales.codacy.com>"
    },
    "auth": {
      "originating_ip": "52.101.193.74",
      "spf": "PASS",
      "dkim": "NEUTRAL",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "A follow-up sales email from Maria Filipe at Codacy to Daniel Tiongco at Pdax, aiming to schedule a call to discuss code quality and security solutions.",
      "category": "Sales",
      "sentiment": "Professional",
      "entities": {
        "people": [
          "Maria Filipe",
          "Daniel Tiongco"
        ],
        "organizations": [
          "Codacy",
          "Pdax"
        ],
        "dates_mentioned": [
          "Fri",
          "17 Apr 2026",
          "Monday",
          "6 April 2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Schedule a quick call in the next few days"
      ]
    },
    "suspicious_urls": [],
    "attachments": []
  },
  {
    "source_file": "Civil Case No. 065 Orders dated May 29 and June 1.eml",
    "risk_level": "MEDIUM",
    "risk_score": 40,
    "indicators": [
      "DKIM body hash did not verify",
      "ARC authentication failed",
      "PDF attachments contain OpenAction directive",
      "Playbook classification: Suspicious"
    ],
    "warning": "",
    "metadata": {
      "subject": "Civil Case No. 065 - Orders dated May 29 and June 1, 2026",
      "from": "RTC Branch 162 Pasig City <rtc1pas162@judiciary.gov.ph>",
      "to": "Litigation <litigation@sterlingbankasia.com>",
      "cc": "\"Carlos Celestino F. Romulo\" <cfromulo@allbank.ph>, \"legal@gotyme.com.ph\" <legal@gotyme.com.ph>, \"legal@uno.bank\" <legal@uno.bank>, \"chay.jandayan@uno.bank\" <chay.jandayan@uno.bank>, \"theresa.veneracion@maya.ph\" <theresa.veneracion@maya.ph>, \"legal.ph@maribank.com.ph\" <legal.ph@maribank.com.ph>, GCash Cases 03 <gcashcases@mynt.xyz>, \"legal@coins.ph\" <legal@coins.ph>, bpilegaloffice <bpilegaloffice@bpi.com.ph>, \"krjose@tonikbank.com\" <krjose@tonikbank.com>, \"legalservices-nonloan@bdo.com.ph\" <legalservices-nonloan@bdo.com.ph>, Jhee Ann Belgica <jabelgica@ownbank.com.ph>, \"hello@cimb.com\" <hello@cimb.com>, \"support@pdax.ph\" <support@pdax.ph>, \"bspmail@bsp.gov.ph\" <bspmail@bsp.gov.ph>, \"support@pdax.ph\" <support@pdax.ph>, \"gladys.z@palawanpay.com\" <gladys.z@palawanpay.com>",
      "reply_to": "",
      "date": "Mon, 01 Jun 2026 08:23:06 +0000",
      "message_id": "<SEYPR04MB6261B2DB81D81B220159FF7FED152@SEYPR04MB6261.apcprd04.prod.outlook.com>"
    },
    "auth": {
      "originating_ip": "52.101.127.32",
      "spf": "PASS",
      "dkim": "NEUTRAL",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "The email transmits electronic copies of court orders dated May 29 and June 1, 2026, for Civil Case No. 065 involving Sterling Bank of Asia and AllBank Inc. It requests acknowledgment of receipt from the recipients.",
      "category": "Legal / Official Correspondence",
      "sentiment": "Formal",
      "entities": {
        "people": [
          "Carlos Celestino F. Romulo",
          "Jhee Ann Belgica"
        ],
        "organizations": [
          "RTC Branch 162 Pasig City",
          "Sterling Bank of Asia",
          "AllBank Inc.",
          "GoTyme",
          "UNO Bank",
          "Maya",
          "Maribank",
          "GCash",
          "Coins.ph",
          "BPI",
          "Tonik Bank",
          "BDO",
          "Ownbank",
          "CIMB",
          "PDAX",
          "BSP",
          "PalawanPay"
        ],
        "dates_mentioned": [
          "May 29",
          "2026",
          "June 1",
          "2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Acknowledge receipt of this email"
      ]
    },
    "suspicious_urls": [],
    "attachments": [
      {
        "filename": "Outlook-v2tevpj1.jpg",
        "type": "jpeg",
        "sha256": "0b615e15a534d743…",
        "flagged": false,
        "reason": "allow"
      },
      {
        "filename": "Civil Case No. 065 - Order dated 05292026.pdf",
        "type": "pdf",
        "sha256": "ab317a661a271a51…",
        "flagged": false,
        "reason": "sandbox_detonation"
      },
      {
        "filename": "Civil Case No. 065 - Order dated 06012026.pdf",
        "type": "pdf",
        "sha256": "efbe8e4198d8d59e…",
        "flagged": false,
        "reason": "sandbox_detonation"
      }
    ]
  },
  {
    "source_file": "Bird Facts.EML",
    "risk_level": "LOW",
    "risk_score": 20,
    "indicators": [
      "dkim_neutral_body_hash_mismatch",
      "unsolicited_content"
    ],
    "warning": "",
    "metadata": {
      "subject": "Bird Facts",
      "from": "RealtimeSave Team <remi@undersmartsupply.com>",
      "to": "erika.pacheco@pdax.ph",
      "cc": "",
      "reply_to": "remi@undersmartsupply.com",
      "date": "Tue, 21 Apr 2026 10:22:04 +0000",
      "message_id": "<UYUBOIYRU5TJS2JOCI4L@undersmartsupply.com>"
    },
    "auth": {
      "originating_ip": "64.43.82.11",
      "spf": "PASS",
      "dkim": "NEUTRAL",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "The email contains a single sentence stating a fact about hummingbirds being the only birds capable of flying backwards. It includes an external email warning banner.",
      "category": "Spam",
      "sentiment": "Neutral",
      "entities": {
        "people": [],
        "organizations": [],
        "dates_mentioned": [],
        "amounts_mentioned": []
      },
      "action_items": []
    },
    "suspicious_urls": [],
    "attachments": []
  },
  {
    "source_file": "BSPCMS-2026-6TWNFHN7SG - 2nd Follow Up_ Request for SOA and Emai.eml",
    "risk_level": "LOW",
    "risk_score": 10,
    "indicators": [
      "Urgency language present regarding 24-hour deadline",
      "Threat of escalation to regulatory body (BSP)",
      "Personal email address used for business dispute"
    ],
    "warning": "",
    "metadata": {
      "subject": "BSPCMS-2026-6TWNFHN7SG - 2nd Follow Up: Request for SOA and Email Logs",
      "from": "JAIRUS ALCARAZ <jairus112489@yahoo.com>",
      "to": "PDAX Support <support@pdax.ph>",
      "cc": "consumeraffairs@bsp.gov.ph",
      "reply_to": "",
      "date": "Fri, 19 Jun 2026 08:04:49 +0000",
      "message_id": "<755832497.99590.1781856289658@mail.yahoo.com>"
    },
    "auth": {
      "originating_ip": "106.10.244.37",
      "spf": "UNKNOWN",
      "dkim": "UNKNOWN",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "Jairus Alcaraz follows up on a request for a Statement of Account and email logs regarding a disputed transaction of ₱261,799, citing BSP Circular No. 1108 and threatening escalation to the Bangko Sentral ng Pilipinas if documents are not provided within 24 hours.",
      "category": "Customer Complaint / Escalation",
      "sentiment": "Urgent / Demanding",
      "entities": {
        "people": [
          "Jairus Alcaraz"
        ],
        "organizations": [
          "PDAX",
          "Bangko Sentral ng Pilipinas",
          "BSP"
        ],
        "dates_mentioned": [
          "June 15",
          "2026",
          "April 20",
          "2026",
          "April 21",
          "2026"
        ],
        "amounts_mentioned": [
          "₱261",
          "799",
          "0.9 ETH",
          "1.86 ETH",
          "PHP 17",
          "247.41"
        ]
      },
      "action_items": [
        "Provide Full Statement of Account showing the April 20, 2026 transactions",
        "Provide Read-only access to account for audit purposes",
        "Provide Email logs of all PDAX notifications sent on April 20-21, 2026"
      ]
    },
    "suspicious_urls": [],
    "attachments": []
  },
  {
    "source_file": "Cannot login even after reset password.eml",
    "risk_level": "LOW",
    "risk_score": 10,
    "indicators": [
      "dkim_body_hash_mismatch"
    ],
    "warning": "",
    "metadata": {
      "subject": "Re: Cannot login even after reset password",
      "from": "CJ - Carmelo John Navarro <cj.navarrocarmelo@gmail.com>",
      "to": "PDAX Support <support@pdax.ph>",
      "cc": "",
      "reply_to": "",
      "date": "Thu, 04 Jun 2026 23:29:47 +0800",
      "message_id": "<CABfgYDwJeb8AzhdF4MR7evESBi5dUaxx9uPbX7aA+E9LqstctA@mail.gmail.com>"
    },
    "auth": {
      "originating_ip": "209.85.208.173",
      "spf": "PASS",
      "dkim": "NEUTRAL",
      "address_mismatch": false,
      "mismatch_details": ""
    },
    "content": {
      "summary": "The user is responding to a support ticket regarding a login issue, providing a Loom video link to demonstrate the problem.",
      "category": "Support",
      "sentiment": "Neutral",
      "entities": {
        "people": [
          "Carmelo John Navarro",
          "Ash"
        ],
        "organizations": [
          "PDAX",
          "Gmail",
          "Loom"
        ],
        "dates_mentioned": [
          "Thu",
          "Jun 4",
          "2026"
        ],
        "amounts_mentioned": []
      },
      "action_items": [
        "Watch the provided Loom video to diagnose the login issue."
      ]
    },
    "suspicious_urls": [],
    "attachments": []
  }
];
