#!/usr/bin/env python3
"""INTERNAL TEST ONLY — simulate SEG gate: samples/ → samples_output/ + spool.

Not the final architecture. Lab exercise only:

  samples/                     = incoming mail
  samples_output/*.eml         = clean/safe mail (stand-in for Google Workspace)
  samples_output/*_GATE.md     = short gate note per delivered message
  gateway/spool/quarantine/    = held for review
  gateway/spool/rejected/      = blocked

Decision (test-only hybrid):
  1. Core run_pipeline verdict/disposition
  2. Playbook (when attachments) — HIGH/CRITICAL escalates even if core is CLEAN
  3. Core MALICIOUS + hard_override → rejected/
  4. Playbook CRITICAL / Malware Delivery → rejected/
  5. Else QUARANTINE-worthy → quarantine/
  6. Else → copy .eml into samples_output/

Usage:
  python3 gateway/internal_inbox_test.py
  python3 gateway/internal_inbox_test.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from app.models import Disposition, EnforceMode, Verdict  # noqa: E402
from app.disposition import decide_disposition  # noqa: E402
from app.pipeline.runner import run_pipeline  # noqa: E402
from eml_analysis_agent import parse_eml  # noqa: E402


def _safe_id(name: str) -> str:
    cleaned = re.sub(r"[^\w.\-@()+]+", "_", name).strip("_")
    return (cleaned[:140] or "msg") + f"_{int(datetime.now(timezone.utc).timestamp())}"


def _playbook_action(pb: dict | None) -> str | None:
    """Map playbook → delivered|quarantined|rejected|None."""
    if not pb:
        return None
    verdict = (pb.get("verdict") or "").upper()
    band = (pb.get("risk_band") or "").upper()
    if "MALWARE" in verdict or band == "CRITICAL":
        return "rejected"
    if band in ("HIGH", "CRITICAL") or "PHISHING" in verdict:
        return "quarantined"
    if band == "MEDIUM" or "SUSPICIOUS" in verdict:
        return "quarantined"
    return None


def _write_spool(bucket: Path, queue_id: str, raw: bytes, meta: dict) -> Path:
    dest = bucket / queue_id
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "message.eml").write_bytes(raw)
    (dest / "meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return dest


def _gate_note(path: Path, eml_name: str, core, pb, action: str) -> None:
    lines = [
        f"# Gateway delivery note — {eml_name}",
        "",
        "**Internal test only — not production architecture.**",
        f"**Delivered at:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"**Gate action:** {action}",
        "",
        "## Core pipeline",
        f"- Verdict: `{core.verdict.value}` (score {core.composite_score})",
        f"- Disposition: `{core.disposition.value}`",
        f"- Reason: {core.disposition_reason}",
    ]
    if core.hard_override:
        lines.append(f"- Hard override: `{core.hard_override}`")
    if core.reasons:
        lines.append("- Flags: " + ", ".join(core.reasons[:12]))
    if pb:
        lines += [
            "",
            "## Forensic playbook",
            f"- Verdict: {pb.get('verdict')}",
            f"- Score: {pb.get('score')}",
        ]
        for f in (pb.get("findings") or [])[:10]:
            lines.append(f"  - {f}")
    lines += ["", "---", "_Generated by `gateway/internal_inbox_test.py`._", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def run_test(samples_dir: Path, inbox_dir: Path, spool: Path, dry_run: bool) -> int:
    inbox_dir.mkdir(parents=True, exist_ok=True)
    (spool / "quarantine").mkdir(parents=True, exist_ok=True)
    (spool / "rejected").mkdir(parents=True, exist_ok=True)

    if not dry_run:
        for p in inbox_dir.glob("*.eml"):
            p.unlink()
        for p in inbox_dir.glob("*_GATE.md"):
            p.unlink()

    emls = sorted(p for p in samples_dir.iterdir()
                  if p.is_file() and p.suffix.lower() == ".eml")
    if not emls:
        print(f"no .eml in {samples_dir}", file=sys.stderr)
        return 1

    print(f"INTERNAL GATEWAY TEST — {len(emls)} incoming")
    print(f"  inbox (clean)  → {inbox_dir}")
    print(f"  quarantine     → {spool / 'quarantine'}")
    print(f"  rejected/block → {spool / 'rejected'}")
    print(f"  dry_run={dry_run}\n")

    counts = {"delivered": 0, "quarantined": 0, "rejected": 0}
    rows = []

    for eml in emls:
        raw = eml.read_bytes()
        core = run_pipeline(raw, source="smtp_hold")
        decide_disposition(core, enforce_mode=EnforceMode.QUARANTINE)

        pb = None
        try:
            parsed = parse_eml(eml)
            pb = parsed.get("playbook")
        except Exception as e:
            pb = {"verdict": "PLAYBOOK_ERROR", "risk_band": "LOW",
                  "score": 0, "findings": [str(e)]}

        # Base action from core disposition
        if core.disposition in (Disposition.DELIVER, Disposition.LOG):
            action = "delivered"
        elif core.disposition == Disposition.REJECT:
            action = "rejected"
        else:
            action = "quarantined"

        # Test-only playbook escalation
        pb_action = _playbook_action(pb)
        if pb_action == "rejected":
            action = "rejected"
        elif pb_action == "quarantined" and action == "delivered":
            action = "quarantined"

        if core.verdict == Verdict.MALICIOUS and core.hard_override:
            action = "rejected"

        meta = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "test": "internal_inbox_test",
            "source_file": eml.name,
            "core_verdict": core.verdict.value,
            "core_score": core.composite_score,
            "core_disposition": core.disposition.value,
            "hard_override": core.hard_override,
            "reasons": core.reasons,
            "playbook": pb,
            "gate_action": action,
            "subject": core.subject,
            "from": core.from_header,
        }
        qid = _safe_id(eml.stem)

        if dry_run:
            print(f"  [{action:12}] core={core.verdict.value:<10} "
                  f"pb={(pb or {}).get('verdict', '-')}  {eml.name}")
        elif action == "delivered":
            shutil.copy2(eml, inbox_dir / eml.name)
            _gate_note(inbox_dir / f"{eml.stem}_GATE.md", eml.name, core, pb, action)
            counts["delivered"] += 1
            print(f"  [delivered   ] samples_output/{eml.name}  "
                  f"(core={core.verdict.value})")
        elif action == "rejected":
            dest = _write_spool(spool / "rejected", qid, raw, meta)
            counts["rejected"] += 1
            print(f"  [rejected    ] {dest.relative_to(_ROOT)}  "
                  f"(core={core.verdict.value}, pb={(pb or {}).get('verdict', '-')})")
        else:
            dest = _write_spool(spool / "quarantine", qid, raw, meta)
            counts["quarantined"] += 1
            print(f"  [quarantined ] {dest.relative_to(_ROOT)}  "
                  f"(core={core.verdict.value}, pb={(pb or {}).get('verdict', '-')})")

        rows.append({"file": eml.name, "action": action,
                     "core": core.verdict.value,
                     "playbook": (pb or {}).get("verdict")})

    print("\n=== SUMMARY ===")
    print(f"  delivered   → samples_output/:        {counts['delivered']}")
    print(f"  quarantined → gateway/spool/quarantine/: {counts['quarantined']}")
    print(f"  rejected    → gateway/spool/rejected/:   {counts['rejected']}")
    if not dry_run:
        summary = spool / "internal_inbox_test_summary.json"
        summary.write_text(json.dumps({
            "ts": datetime.now(timezone.utc).isoformat(),
            "note": "INTERNAL TEST ONLY — not production architecture",
            "counts": counts,
            "rows": rows,
        }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"  summary     → {summary.relative_to(_ROOT)}")
        print("\nList spool: python3 gateway/hold_consumer.py --list")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--samples", default=str(_ROOT / "samples"))
    ap.add_argument("--inbox", default=str(_ROOT / "samples_output"))
    ap.add_argument("--spool", default=str(_ROOT / "gateway" / "spool"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)
    return run_test(Path(args.samples), Path(args.inbox), Path(args.spool), args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
